### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by teto** [tjdevries/descriptive_maps.vim#1]
Just ran :call DescriptiveMaps() on nvim-dev
```
Erreur détectée en traitant function DescriptiveStart :         
ligne    1 :                                                                                                                                                       
error caught in request handler '/home/teto/.local/share/nvim/site/pack/descriptive_maps.vim/rplugin/python3/descriptive_maps:function:DescriptiveStart [[]]':     
Traceback (most recent call last):                                                                                                                                 
  File "/home/teto/.local/share/nvim/site/pack/descriptive_maps.vim/rplugin/python3/descriptive_maps/__init__.py", line 26, in start                               
    status = self.desc.start()                                                                                                                                     
  File "/home/teto/.local/share/nvim/site/pack/descriptive_maps.vim/rplugin/python3/descriptive_maps/descriptor.py", line 44, in start                             
    return super().start()                                                                                                                                         
  File "/home/teto/.local/share/nvim/site/pack/descriptive_maps.vim/rplugin/python3/descriptive_maps/prompt/prompt.py", line 166, in start                         
    status = self.on_update(status) or STATUS_PROGRESS                                                                                                             
  File "/home/teto/.local/share/nvim/site/pack/descriptive_maps.vim/rplugin/python3/descriptive_maps/descriptor.py", line 79, in on_update                         
    self.result = applicable_keys[self.nvim.call('line', ['.']) - 1]                                                                                               
IndexError: list index out of range 
```

**Comment by tjdevries** [comment]
Thanks for trying this out! I will take a look at that sometime over the next couple days.

Trying to get https://github.com/neovim/neovim/pull/6236 merged so that I can get rid of a lot of hacks to get proper information on users mappings.

**Comment by teto** [comment]
that can wait for your patch to be merged, I don't actively use the plugin. Just realized it was installed and wanted to give it a spin then I had this error. Thought I would let you know just in case.

**Comment by tjdevries** [comment]
Maybe you could try it again, I just pushed some fixes. had time during lunch :)

**Comment by teto** [comment]
Problem solved ! It's already quite cool you have a lot more stars.
Now I would need to load the list into fzf :)
Thanks

**Comment by tjdevries** [comment]
Glad you like it and it works again! I think I left off in the middle of a bit of a refactor but glad I got it sorted out now.
